<?php

{{pretext}}

/*****************************************************
 * This file was auto-generated by pho-compiler
 * For more information, visit http://phonetworks.org
 ******************************************************/

class {{ class_name }} extends {{ extends }} {

    {{# traits }}
    use {{ . }}
    {{/ traits }}
    


}

/*****************************************************
 * Timestamp: {{ compilation_timestamp }}
 * Size (in bytes): {{ size_in_bytes }}
 * Compilation Time: {{ compilation_time }}
 * {{ hash }}
 ******************************************************/