<?php

{{pretext}}

/*****************************************************
 * This file was auto-generated by pho-compiler
 * For more information, visit http://phonetworks.org
 ******************************************************/

class {{class_name}} extends {{extends}} {


    
}

/*****************************************************
 * Timestamp: {{compilation_timestamp}}
 * Size (in bytes): {{bytes}}
 * Compilation Time: {{compiltion_time}}
 * {{hash}}
 ******************************************************/